# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  ca_org1:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-cli-server
      - SOFTHSM2_CONF=/etc/hyperledger/fabric/softhsm2.conf
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
      - ../organizations/peerOrganizations/org1.example.com:/etc/hyperledger/fabric-ca-cli-server
      - ../softhsm/softhsm2.conf:/etc/hyperledger/fabric/softhsm2.conf
      # - ../softhsm/libsofthsm2.so:/etc/hyperledger/fabric/libsofthsm2.so
      - ../softhsm/tokens:/etc/hyperledger/fabric/softhsm/tokens
    container_name: ca_org1
    networks:
      - test

  ca_org2:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-cli-server
      - SOFTHSM2_CONF=/etc/hyperledger/fabric/softhsm2.conf
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
      - ../organizations/peerOrganizations/org2.example.com:/etc/hyperledger/fabric-ca-cli-server
      - ../softhsm/softhsm2.conf:/etc/hyperledger/fabric/softhsm2.conf
      # - ../softhsm/libsofthsm2.so:/etc/hyperledger/fabric/libsofthsm2.so
      - ../softhsm/tokens:/etc/hyperledger/fabric/softhsm/tokens
    container_name: ca_org2
    networks:
      - test

  ca_orderer:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-cli-server
      - SOFTHSM2_CONF=/etc/hyperledger/fabric/softhsm2.conf
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
      - ../organizations/ordererOrganizations/example.com:/etc/hyperledger/fabric-ca-cli-server
      - ../softhsm/softhsm2.conf:/etc/hyperledger/fabric/softhsm2.conf
      # - ../softhsm/libsofthsm2.so:/etc/hyperledger/fabric/libsofthsm2.so
      - ../softhsm/tokens:/etc/hyperledger/fabric/softhsm/tokens
    container_name: ca_orderer
    networks:
      - test
